{"cells":[{"cell_type":"markdown","source":["<img src=\"https://databricks.com/wp-content/uploads/2021/09/Machine-Learning-lakehouse-architecture.png\" width=1012/>\"\""],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"a9d6b5ed-9a67-422c-be4a-1791abcfe646"}}},{"cell_type":"markdown","source":["# Databricks ML Quickstart: Model Training\n\nThis notebook provides a quick overview of machine learning model training on Databricks. To train models, you can use libraries like scikit-learn that are preinstalled on the Databricks Runtime for Machine Learning. In addition, you can use MLflow to track the trained models, and Hyperopt with SparkTrials to scale hyperparameter tuning.\n\nThis tutorial covers:\n- Part 1: Training a simple classification model with MLflow tracking\n- Part 2: Hyperparameter tuning a better performing model with Hyperopt\n\nFor more details on productionizing machine learning on Databricks including model lifecycle management and model inference, see the ML End to End Example ([AWS](https://docs.databricks.com/applications/mlflow/end-to-end-example.html)|[Azure](https://docs.microsoft.com/azure/databricks/applications/mlflow/end-to-end-example)|[GCP](https://docs.gcp.databricks.com/applications/mlflow/end-to-end-example.html)).\n\n### Requirements\n- Cluster running Databricks Runtime 7.5 ML or above"],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"528c6d2b-3c5a-4236-ac61-fa8cc8d4d323"}}},{"cell_type":"markdown","source":["### Libraries\nImport the necessary libraries. These libraries are preinstalled on Databricks Runtime for Machine Learning ([AWS](https://docs.databricks.com/runtime/mlruntime.html)|[Azure](https://docs.microsoft.com/azure/databricks/runtime/mlruntime)|[GCP](https://docs.gcp.databricks.com/runtime/mlruntime.html)) clusters and are tuned for compatibility and performance."],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"8738a402-24dc-4074-bebb-b51bec8e74db"}}},{"cell_type":"code","source":["#%sh\n#pip3 install mlflow\n#pip3 install hyperopt"],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"8397fc41-1c32-4ad1-9880-e6ab8211c24d"}},"outputs":[{"output_type":"display_data","metadata":{"application/vnd.databricks.v1+output":{"datasetInfos":[],"data":"<div class=\"ansiout\">Requirement already satisfied: mlflow in /databricks/python3/lib/python3.8/site-packages (1.24.0)\nRequirement already satisfied: pytz in /databricks/python3/lib/python3.8/site-packages (from mlflow) (2020.5)\nRequirement already satisfied: Flask in /databricks/python3/lib/python3.8/site-packages (from mlflow) (2.0.3)\nRequirement already satisfied: sqlalchemy in /databricks/python3/lib/python3.8/site-packages (from mlflow) (1.4.32)\nRequirement already satisfied: scipy in /databricks/python3/lib/python3.8/site-packages (from mlflow) (1.6.2)\nRequirement already satisfied: alembic in /databricks/python3/lib/python3.8/site-packages (from mlflow) (1.7.7)\nRequirement already satisfied: pandas in /databricks/python3/lib/python3.8/site-packages (from mlflow) (1.2.4)\nRequirement already satisfied: sqlparse&gt;=0.3.1 in /databricks/python3/lib/python3.8/site-packages (from mlflow) (0.4.2)\nRequirement already satisfied: gitpython&gt;=2.1.0 in /databricks/python3/lib/python3.8/site-packages (from mlflow) (3.1.27)\nRequirement already satisfied: numpy in /databricks/python3/lib/python3.8/site-packages (from mlflow) (1.19.2)\nRequirement already satisfied: databricks-cli&gt;=0.8.7 in /databricks/python3/lib/python3.8/site-packages (from mlflow) (0.16.4)\nRequirement already satisfied: packaging in /databricks/python3/lib/python3.8/site-packages (from mlflow) (20.9)\nRequirement already satisfied: protobuf&gt;=3.7.0 in /databricks/python3/lib/python3.8/site-packages (from mlflow) (3.17.2)\nRequirement already satisfied: requests&gt;=2.17.3 in /databricks/python3/lib/python3.8/site-packages (from mlflow) (2.25.1)\nRequirement already satisfied: cloudpickle in /databricks/python3/lib/python3.8/site-packages (from mlflow) (2.0.0)\nRequirement already satisfied: click&gt;=7.0 in /databricks/python3/lib/python3.8/site-packages (from mlflow) (8.0.4)\nRequirement already satisfied: gunicorn in /databricks/python3/lib/python3.8/site-packages (from mlflow) (20.1.0)\nRequirement already satisfied: docker&gt;=4.0.0 in /databricks/python3/lib/python3.8/site-packages (from mlflow) (5.0.3)\nRequirement already satisfied: querystring-parser in /databricks/python3/lib/python3.8/site-packages (from mlflow) (1.2.4)\nRequirement already satisfied: pyyaml&gt;=5.1 in /databricks/python3/lib/python3.8/site-packages (from mlflow) (6.0)\nRequirement already satisfied: importlib-metadata!=4.7.0,&gt;=3.7.0 in /databricks/python3/lib/python3.8/site-packages (from mlflow) (4.11.3)\nRequirement already satisfied: entrypoints in /databricks/python3/lib/python3.8/site-packages (from mlflow) (0.3)\nRequirement already satisfied: prometheus-flask-exporter in /databricks/python3/lib/python3.8/site-packages (from mlflow) (0.19.0)\nRequirement already satisfied: six&gt;=1.10.0 in /databricks/python3/lib/python3.8/site-packages (from databricks-cli&gt;=0.8.7-&gt;mlflow) (1.15.0)\nRequirement already satisfied: tabulate&gt;=0.7.7 in /databricks/python3/lib/python3.8/site-packages (from databricks-cli&gt;=0.8.7-&gt;mlflow) (0.8.9)\nRequirement already satisfied: websocket-client&gt;=0.32.0 in /databricks/python3/lib/python3.8/site-packages (from docker&gt;=4.0.0-&gt;mlflow) (1.3.1)\nRequirement already satisfied: gitdb&lt;5,&gt;=4.0.1 in /databricks/python3/lib/python3.8/site-packages (from gitpython&gt;=2.1.0-&gt;mlflow) (4.0.9)\nRequirement already satisfied: smmap&lt;6,&gt;=3.0.1 in /databricks/python3/lib/python3.8/site-packages (from gitdb&lt;5,&gt;=4.0.1-&gt;gitpython&gt;=2.1.0-&gt;mlflow) (5.0.0)\nRequirement already satisfied: zipp&gt;=0.5 in /databricks/python3/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,&gt;=3.7.0-&gt;mlflow) (3.7.0)\nRequirement already satisfied: certifi&gt;=2017.4.17 in /databricks/python3/lib/python3.8/site-packages (from requests&gt;=2.17.3-&gt;mlflow) (2020.12.5)\nRequirement already satisfied: chardet&lt;5,&gt;=3.0.2 in /databricks/python3/lib/python3.8/site-packages (from requests&gt;=2.17.3-&gt;mlflow) (4.0.0)\nRequirement already satisfied: urllib3&lt;1.27,&gt;=1.21.1 in /databricks/python3/lib/python3.8/site-packages (from requests&gt;=2.17.3-&gt;mlflow) (1.25.11)\nRequirement already satisfied: idna&lt;3,&gt;=2.5 in /databricks/python3/lib/python3.8/site-packages (from requests&gt;=2.17.3-&gt;mlflow) (2.10)\nRequirement already satisfied: importlib-resources in /databricks/python3/lib/python3.8/site-packages (from alembic-&gt;mlflow) (5.4.0)\nRequirement already satisfied: Mako in /databricks/python3/lib/python3.8/site-packages (from alembic-&gt;mlflow) (1.2.0)\nRequirement already satisfied: greenlet!=0.4.17 in /databricks/python3/lib/python3.8/site-packages (from sqlalchemy-&gt;mlflow) (1.1.2)\nRequirement already satisfied: Werkzeug&gt;=2.0 in /databricks/python3/lib/python3.8/site-packages (from Flask-&gt;mlflow) (2.0.3)\nRequirement already satisfied: Jinja2&gt;=3.0 in /databricks/python3/lib/python3.8/site-packages (from Flask-&gt;mlflow) (3.0.3)\nRequirement already satisfied: itsdangerous&gt;=2.0 in /databricks/python3/lib/python3.8/site-packages (from Flask-&gt;mlflow) (2.1.1)\nRequirement already satisfied: MarkupSafe&gt;=2.0 in /databricks/python3/lib/python3.8/site-packages (from Jinja2&gt;=3.0-&gt;Flask-&gt;mlflow) (2.1.1)\nRequirement already satisfied: setuptools&gt;=3.0 in /usr/local/lib/python3.8/dist-packages (from gunicorn-&gt;mlflow) (52.0.0)\nRequirement already satisfied: pyparsing&gt;=2.0.2 in /databricks/python3/lib/python3.8/site-packages (from packaging-&gt;mlflow) (2.4.7)\nRequirement already satisfied: python-dateutil&gt;=2.7.3 in /databricks/python3/lib/python3.8/site-packages (from pandas-&gt;mlflow) (2.8.1)\nRequirement already satisfied: prometheus-client in /databricks/python3/lib/python3.8/site-packages (from prometheus-flask-exporter-&gt;mlflow) (0.10.1)\nWARNING: You are using pip version 21.0.1; however, version 22.0.4 is available.\nYou should consider upgrading via the &#39;/databricks/python3/bin/python -m pip install --upgrade pip&#39; command.\nCollecting hyperopt\n  Downloading hyperopt-0.2.7-py2.py3-none-any.whl (1.6 MB)\nRequirement already satisfied: six in /databricks/python3/lib/python3.8/site-packages (from hyperopt) (1.15.0)\nCollecting py4j\n  Downloading py4j-0.10.9.5-py2.py3-none-any.whl (199 kB)\nCollecting tqdm\n  Downloading tqdm-4.63.0-py2.py3-none-any.whl (76 kB)\nRequirement already satisfied: numpy in /databricks/python3/lib/python3.8/site-packages (from hyperopt) (1.19.2)\nRequirement already satisfied: scipy in /databricks/python3/lib/python3.8/site-packages (from hyperopt) (1.6.2)\nCollecting networkx&gt;=2.2\n  Downloading networkx-2.7.1-py3-none-any.whl (2.0 MB)\nRequirement already satisfied: cloudpickle in /databricks/python3/lib/python3.8/site-packages (from hyperopt) (2.0.0)\nCollecting future\n  Downloading future-0.18.2.tar.gz (829 kB)\nBuilding wheels for collected packages: future\n  Building wheel for future (setup.py): started\n  Building wheel for future (setup.py): finished with status &#39;done&#39;\n  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491059 sha256=e9db994e483ef9f4080b56d8fc4f676385a41072a21f82fb5e44689febb4d5af\n  Stored in directory: /root/.cache/pip/wheels/8e/70/28/3d6ccd6e315f65f245da085482a2e1c7d14b90b30f239e2cf4\nSuccessfully built future\nInstalling collected packages: tqdm, py4j, networkx, future, hyperopt\nSuccessfully installed future-0.18.2 hyperopt-0.2.7 networkx-2.7.1 py4j-0.10.9.5 tqdm-4.63.0\nWARNING: You are using pip version 21.0.1; however, version 22.0.4 is available.\nYou should consider upgrading via the &#39;/databricks/python3/bin/python -m pip install --upgrade pip&#39; command.\n</div>","removedWidgets":[],"addedWidgets":{},"metadata":{},"type":"html","arguments":{}}},"output_type":"display_data","data":{"text/html":["<style scoped>\n  .ansiout {\n    display: block;\n    unicode-bidi: embed;\n    white-space: pre-wrap;\n    word-wrap: break-word;\n    word-break: break-all;\n    font-family: \"Source Code Pro\", \"Menlo\", monospace;;\n    font-size: 13px;\n    color: #555;\n    margin-left: 4px;\n    line-height: 19px;\n  }\n</style>\n<div class=\"ansiout\">Requirement already satisfied: mlflow in /databricks/python3/lib/python3.8/site-packages (1.24.0)\nRequirement already satisfied: pytz in /databricks/python3/lib/python3.8/site-packages (from mlflow) (2020.5)\nRequirement already satisfied: Flask in /databricks/python3/lib/python3.8/site-packages (from mlflow) (2.0.3)\nRequirement already satisfied: sqlalchemy in /databricks/python3/lib/python3.8/site-packages (from mlflow) (1.4.32)\nRequirement already satisfied: scipy in /databricks/python3/lib/python3.8/site-packages (from mlflow) (1.6.2)\nRequirement already satisfied: alembic in /databricks/python3/lib/python3.8/site-packages (from mlflow) (1.7.7)\nRequirement already satisfied: pandas in /databricks/python3/lib/python3.8/site-packages (from mlflow) (1.2.4)\nRequirement already satisfied: sqlparse&gt;=0.3.1 in /databricks/python3/lib/python3.8/site-packages (from mlflow) (0.4.2)\nRequirement already satisfied: gitpython&gt;=2.1.0 in /databricks/python3/lib/python3.8/site-packages (from mlflow) (3.1.27)\nRequirement already satisfied: numpy in /databricks/python3/lib/python3.8/site-packages (from mlflow) (1.19.2)\nRequirement already satisfied: databricks-cli&gt;=0.8.7 in /databricks/python3/lib/python3.8/site-packages (from mlflow) (0.16.4)\nRequirement already satisfied: packaging in /databricks/python3/lib/python3.8/site-packages (from mlflow) (20.9)\nRequirement already satisfied: protobuf&gt;=3.7.0 in /databricks/python3/lib/python3.8/site-packages (from mlflow) (3.17.2)\nRequirement already satisfied: requests&gt;=2.17.3 in /databricks/python3/lib/python3.8/site-packages (from mlflow) (2.25.1)\nRequirement already satisfied: cloudpickle in /databricks/python3/lib/python3.8/site-packages (from mlflow) (2.0.0)\nRequirement already satisfied: click&gt;=7.0 in /databricks/python3/lib/python3.8/site-packages (from mlflow) (8.0.4)\nRequirement already satisfied: gunicorn in /databricks/python3/lib/python3.8/site-packages (from mlflow) (20.1.0)\nRequirement already satisfied: docker&gt;=4.0.0 in /databricks/python3/lib/python3.8/site-packages (from mlflow) (5.0.3)\nRequirement already satisfied: querystring-parser in /databricks/python3/lib/python3.8/site-packages (from mlflow) (1.2.4)\nRequirement already satisfied: pyyaml&gt;=5.1 in /databricks/python3/lib/python3.8/site-packages (from mlflow) (6.0)\nRequirement already satisfied: importlib-metadata!=4.7.0,&gt;=3.7.0 in /databricks/python3/lib/python3.8/site-packages (from mlflow) (4.11.3)\nRequirement already satisfied: entrypoints in /databricks/python3/lib/python3.8/site-packages (from mlflow) (0.3)\nRequirement already satisfied: prometheus-flask-exporter in /databricks/python3/lib/python3.8/site-packages (from mlflow) (0.19.0)\nRequirement already satisfied: six&gt;=1.10.0 in /databricks/python3/lib/python3.8/site-packages (from databricks-cli&gt;=0.8.7-&gt;mlflow) (1.15.0)\nRequirement already satisfied: tabulate&gt;=0.7.7 in /databricks/python3/lib/python3.8/site-packages (from databricks-cli&gt;=0.8.7-&gt;mlflow) (0.8.9)\nRequirement already satisfied: websocket-client&gt;=0.32.0 in /databricks/python3/lib/python3.8/site-packages (from docker&gt;=4.0.0-&gt;mlflow) (1.3.1)\nRequirement already satisfied: gitdb&lt;5,&gt;=4.0.1 in /databricks/python3/lib/python3.8/site-packages (from gitpython&gt;=2.1.0-&gt;mlflow) (4.0.9)\nRequirement already satisfied: smmap&lt;6,&gt;=3.0.1 in /databricks/python3/lib/python3.8/site-packages (from gitdb&lt;5,&gt;=4.0.1-&gt;gitpython&gt;=2.1.0-&gt;mlflow) (5.0.0)\nRequirement already satisfied: zipp&gt;=0.5 in /databricks/python3/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,&gt;=3.7.0-&gt;mlflow) (3.7.0)\nRequirement already satisfied: certifi&gt;=2017.4.17 in /databricks/python3/lib/python3.8/site-packages (from requests&gt;=2.17.3-&gt;mlflow) (2020.12.5)\nRequirement already satisfied: chardet&lt;5,&gt;=3.0.2 in /databricks/python3/lib/python3.8/site-packages (from requests&gt;=2.17.3-&gt;mlflow) (4.0.0)\nRequirement already satisfied: urllib3&lt;1.27,&gt;=1.21.1 in /databricks/python3/lib/python3.8/site-packages (from requests&gt;=2.17.3-&gt;mlflow) (1.25.11)\nRequirement already satisfied: idna&lt;3,&gt;=2.5 in /databricks/python3/lib/python3.8/site-packages (from requests&gt;=2.17.3-&gt;mlflow) (2.10)\nRequirement already satisfied: importlib-resources in /databricks/python3/lib/python3.8/site-packages (from alembic-&gt;mlflow) (5.4.0)\nRequirement already satisfied: Mako in /databricks/python3/lib/python3.8/site-packages (from alembic-&gt;mlflow) (1.2.0)\nRequirement already satisfied: greenlet!=0.4.17 in /databricks/python3/lib/python3.8/site-packages (from sqlalchemy-&gt;mlflow) (1.1.2)\nRequirement already satisfied: Werkzeug&gt;=2.0 in /databricks/python3/lib/python3.8/site-packages (from Flask-&gt;mlflow) (2.0.3)\nRequirement already satisfied: Jinja2&gt;=3.0 in /databricks/python3/lib/python3.8/site-packages (from Flask-&gt;mlflow) (3.0.3)\nRequirement already satisfied: itsdangerous&gt;=2.0 in /databricks/python3/lib/python3.8/site-packages (from Flask-&gt;mlflow) (2.1.1)\nRequirement already satisfied: MarkupSafe&gt;=2.0 in /databricks/python3/lib/python3.8/site-packages (from Jinja2&gt;=3.0-&gt;Flask-&gt;mlflow) (2.1.1)\nRequirement already satisfied: setuptools&gt;=3.0 in /usr/local/lib/python3.8/dist-packages (from gunicorn-&gt;mlflow) (52.0.0)\nRequirement already satisfied: pyparsing&gt;=2.0.2 in /databricks/python3/lib/python3.8/site-packages (from packaging-&gt;mlflow) (2.4.7)\nRequirement already satisfied: python-dateutil&gt;=2.7.3 in /databricks/python3/lib/python3.8/site-packages (from pandas-&gt;mlflow) (2.8.1)\nRequirement already satisfied: prometheus-client in /databricks/python3/lib/python3.8/site-packages (from prometheus-flask-exporter-&gt;mlflow) (0.10.1)\nWARNING: You are using pip version 21.0.1; however, version 22.0.4 is available.\nYou should consider upgrading via the &#39;/databricks/python3/bin/python -m pip install --upgrade pip&#39; command.\nCollecting hyperopt\n  Downloading hyperopt-0.2.7-py2.py3-none-any.whl (1.6 MB)\nRequirement already satisfied: six in /databricks/python3/lib/python3.8/site-packages (from hyperopt) (1.15.0)\nCollecting py4j\n  Downloading py4j-0.10.9.5-py2.py3-none-any.whl (199 kB)\nCollecting tqdm\n  Downloading tqdm-4.63.0-py2.py3-none-any.whl (76 kB)\nRequirement already satisfied: numpy in /databricks/python3/lib/python3.8/site-packages (from hyperopt) (1.19.2)\nRequirement already satisfied: scipy in /databricks/python3/lib/python3.8/site-packages (from hyperopt) (1.6.2)\nCollecting networkx&gt;=2.2\n  Downloading networkx-2.7.1-py3-none-any.whl (2.0 MB)\nRequirement already satisfied: cloudpickle in /databricks/python3/lib/python3.8/site-packages (from hyperopt) (2.0.0)\nCollecting future\n  Downloading future-0.18.2.tar.gz (829 kB)\nBuilding wheels for collected packages: future\n  Building wheel for future (setup.py): started\n  Building wheel for future (setup.py): finished with status &#39;done&#39;\n  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491059 sha256=e9db994e483ef9f4080b56d8fc4f676385a41072a21f82fb5e44689febb4d5af\n  Stored in directory: /root/.cache/pip/wheels/8e/70/28/3d6ccd6e315f65f245da085482a2e1c7d14b90b30f239e2cf4\nSuccessfully built future\nInstalling collected packages: tqdm, py4j, networkx, future, hyperopt\nSuccessfully installed future-0.18.2 hyperopt-0.2.7 networkx-2.7.1 py4j-0.10.9.5 tqdm-4.63.0\nWARNING: You are using pip version 21.0.1; however, version 22.0.4 is available.\nYou should consider upgrading via the &#39;/databricks/python3/bin/python -m pip install --upgrade pip&#39; command.\n</div>"]}}],"execution_count":0},{"cell_type":"code","source":["import mlflow\nimport numpy as np\nimport pandas as pd\nimport sklearn.datasets\nimport sklearn.metrics\nimport sklearn.model_selection\nimport sklearn.ensemble\n\nfrom hyperopt import fmin, tpe, hp, SparkTrials, Trials, STATUS_OK\nfrom hyperopt.pyll import scope\n\nimport warnings\nwarnings.filterwarnings(\"ignore\")"],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"cec61d6d-ea1a-4d2f-9ee6-625393a24aa5"}},"outputs":[{"output_type":"display_data","metadata":{"application/vnd.databricks.v1+output":{"datasetInfos":[],"data":"<div class=\"ansiout\"></div>","removedWidgets":[],"addedWidgets":{},"metadata":{},"type":"html","arguments":{}}},"output_type":"display_data","data":{"text/html":["<style scoped>\n  .ansiout {\n    display: block;\n    unicode-bidi: embed;\n    white-space: pre-wrap;\n    word-wrap: break-word;\n    word-break: break-all;\n    font-family: \"Source Code Pro\", \"Menlo\", monospace;;\n    font-size: 13px;\n    color: #555;\n    margin-left: 4px;\n    line-height: 19px;\n  }\n</style>\n<div class=\"ansiout\"></div>"]}}],"execution_count":0},{"cell_type":"markdown","source":["### Load data\nThe tutorial uses a dataset describing different wine samples. The [dataset](https://archive.ics.uci.edu/ml/datasets/Wine) is from the UCI Machine Learning Repository and is included in DBFS ([AWS](https://docs.databricks.com/data/databricks-file-system.html)|[Azure](https://docs.microsoft.com/azure/databricks/data/databricks-file-system)|[GCP](https://docs.gcp.databricks.com/data/databricks-file-system.html)).\nThe goal is to classify red and white wines by their quality. \n\nFor more details on uploading and loading from other data sources, see the documentation on working with data ([AWS](https://docs.databricks.com/data/index.html)|[Azure](https://docs.microsoft.com/azure/databricks/data/index)|[GCP](https://docs.gcp.databricks.com/data/index.html))."],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"b2f67ffe-ad1b-49a1-a7cf-603daa8c9890"}}},{"cell_type":"code","source":["# Load and preprocess data\nwhite_wine = pd.read_csv(\"/dbfs/databricks-datasets/wine-quality/winequality-white.csv\", sep=';')\nred_wine = pd.read_csv(\"/dbfs/databricks-datasets/wine-quality/winequality-red.csv\", sep=';')\nwhite_wine['is_red'] = 0.0\nred_wine['is_red'] = 1.0\ndata_df = pd.concat([white_wine, red_wine], axis=0)\n\n# Define classification labels based on the wine quality\ndata_labels = data_df['quality'] >= 7\ndata_df = data_df.drop(['quality'], axis=1)\n\n# Split 80/20 train-test\nX_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(\n  data_df,\n  data_labels,\n  test_size=0.2,\n  random_state=1\n)"],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"51fd8a9f-bef3-4fbd-90ce-8531f5f71205"}},"outputs":[{"output_type":"display_data","metadata":{"application/vnd.databricks.v1+output":{"datasetInfos":[],"data":"<div class=\"ansiout\"></div>","removedWidgets":[],"addedWidgets":{},"metadata":{},"type":"html","arguments":{}}},"output_type":"display_data","data":{"text/html":["<style scoped>\n  .ansiout {\n    display: block;\n    unicode-bidi: embed;\n    white-space: pre-wrap;\n    word-wrap: break-word;\n    word-break: break-all;\n    font-family: \"Source Code Pro\", \"Menlo\", monospace;;\n    font-size: 13px;\n    color: #555;\n    margin-left: 4px;\n    line-height: 19px;\n  }\n</style>\n<div class=\"ansiout\"></div>"]}}],"execution_count":0},{"cell_type":"markdown","source":["## Part 1. Train a classification model"],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"8123df40-67fa-43d0-97c1-6f608c9f7d61"}}},{"cell_type":"markdown","source":["### MLflow Tracking\n[MLflow tracking](https://www.mlflow.org/docs/latest/tracking.html) allows you to organize your machine learning training code, parameters, and models. \n\nYou can enable automatic MLflow tracking by using [*autologging*](https://www.mlflow.org/docs/latest/tracking.html#automatic-logging)."],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"f3441df0-a7fe-4d6d-bf62-46184cf6ac2c"}}},{"cell_type":"code","source":["# Enable MLflow autologging for this notebook\nmlflow.autolog()"],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"18e0381e-7c02-4e57-b29b-127a7585992b"}},"outputs":[{"output_type":"display_data","metadata":{"application/vnd.databricks.v1+output":{"datasetInfos":[],"data":"<div class=\"ansiout\">2022/03/19 19:55:08 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.\n2022/03/19 19:55:08 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:08 INFO mlflow.tracking.fluent: Autologging successfully enabled for pyspark.ml.\n</div>","removedWidgets":[],"addedWidgets":{},"metadata":{},"type":"html","arguments":{}}},"output_type":"display_data","data":{"text/html":["<style scoped>\n  .ansiout {\n    display: block;\n    unicode-bidi: embed;\n    white-space: pre-wrap;\n    word-wrap: break-word;\n    word-break: break-all;\n    font-family: \"Source Code Pro\", \"Menlo\", monospace;;\n    font-size: 13px;\n    color: #555;\n    margin-left: 4px;\n    line-height: 19px;\n  }\n</style>\n<div class=\"ansiout\">2022/03/19 19:55:08 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.\n2022/03/19 19:55:08 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:08 INFO mlflow.tracking.fluent: Autologging successfully enabled for pyspark.ml.\n</div>"]}}],"execution_count":0},{"cell_type":"markdown","source":["Next, train a classifier within the context of an MLflow run, which automatically logs the trained model and many associated metrics and parameters. \n\nYou can supplement the logging with additional metrics such as the model's AUC score on the test dataset."],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"88913160-61c4-4cbf-8f2d-235e86fa8768"}}},{"cell_type":"code","source":["with mlflow.start_run(run_name='gradient_boost') as run:\n  model = sklearn.ensemble.GradientBoostingClassifier(random_state=0)\n  \n  # Models, parameters, and training metrics are tracked automatically\n  model.fit(X_train, y_train)\n\n  predicted_probs = model.predict_proba(X_test)\n  roc_auc = sklearn.metrics.roc_auc_score(y_test, predicted_probs[:,1])\n  \n  # The AUC score on test data is not automatically logged, so log it manually\n  mlflow.log_metric(\"test_auc\", roc_auc)\n  print(\"Test AUC of: {}\".format(roc_auc))"],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"70fefb47-9af8-49c8-932d-49a0727c1428"}},"outputs":[{"output_type":"display_data","metadata":{"application/vnd.databricks.v1+output":{"datasetInfos":[],"data":"<div class=\"ansiout\">2022/03/19 19:55:23 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:23 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:23 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:23 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:23 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:23 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:23 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:23 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:23 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:25 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:28 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:28 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:28 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\nTest AUC of: 0.8834365701533531\n2022/03/19 19:55:28 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:28 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:28 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n</div>","removedWidgets":[],"addedWidgets":{},"metadata":{},"type":"html","arguments":{}}},"output_type":"display_data","data":{"text/html":["<style scoped>\n  .ansiout {\n    display: block;\n    unicode-bidi: embed;\n    white-space: pre-wrap;\n    word-wrap: break-word;\n    word-break: break-all;\n    font-family: \"Source Code Pro\", \"Menlo\", monospace;;\n    font-size: 13px;\n    color: #555;\n    margin-left: 4px;\n    line-height: 19px;\n  }\n</style>\n<div class=\"ansiout\">2022/03/19 19:55:23 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:23 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:23 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:23 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:23 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:23 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:23 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:23 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:23 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:25 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:28 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:28 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:28 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\nTest AUC of: 0.8834365701533531\n2022/03/19 19:55:28 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:28 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:28 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n</div>"]}}],"execution_count":0},{"cell_type":"markdown","source":["If you aren't happy with the performance of this model, train another model with different hyperparameters."],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"06eadee7-a786-4a6a-be73-c70a7c18c0a0"}}},{"cell_type":"code","source":["# Start a new run and assign a run_name for future reference\nwith mlflow.start_run(run_name='gradient_boost') as run:\n  model_2 = sklearn.ensemble.GradientBoostingClassifier(\n    random_state=0, \n    \n    # Try a new parameter setting for n_estimators\n    n_estimators=200,\n  )\n  model_2.fit(X_train, y_train)\n\n  predicted_probs = model_2.predict_proba(X_test)\n  roc_auc = sklearn.metrics.roc_auc_score(y_test, predicted_probs[:,1])\n  mlflow.log_metric(\"test_auc\", roc_auc)\n  print(\"Test AUC of: {}\".format(roc_auc))"],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"85fa6e22-56ab-44da-89c0-e77f883c5fcd"}},"outputs":[{"output_type":"display_data","metadata":{"application/vnd.databricks.v1+output":{"datasetInfos":[],"data":"<div class=\"ansiout\">2022/03/19 19:55:36 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:36 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:36 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:36 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:36 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:36 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:36 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:36 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:36 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:42 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:42 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:42 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\nTest AUC of: 0.8914761673151751\n2022/03/19 19:55:42 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:42 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:42 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n</div>","removedWidgets":[],"addedWidgets":{},"metadata":{},"type":"html","arguments":{}}},"output_type":"display_data","data":{"text/html":["<style scoped>\n  .ansiout {\n    display: block;\n    unicode-bidi: embed;\n    white-space: pre-wrap;\n    word-wrap: break-word;\n    word-break: break-all;\n    font-family: \"Source Code Pro\", \"Menlo\", monospace;;\n    font-size: 13px;\n    color: #555;\n    margin-left: 4px;\n    line-height: 19px;\n  }\n</style>\n<div class=\"ansiout\">2022/03/19 19:55:36 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:36 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:36 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:36 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:36 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:36 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:36 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:36 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:36 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:42 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:42 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:42 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\nTest AUC of: 0.8914761673151751\n2022/03/19 19:55:42 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:42 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:42 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n</div>"]}}],"execution_count":0},{"cell_type":"markdown","source":["### View MLflow runs\nTo view the logged training runs, click the **Experiment** icon at the upper right of the notebook to display the experiment sidebar. If necessary, click the refresh icon to fetch and monitor the latest runs. \n\n<img width=\"350\" src=\"https://docs.databricks.com/_static/images/mlflow/quickstart/experiment-sidebar-icons.png\"/>\n\nYou can then click the experiment page icon to display the more detailed MLflow experiment page ([AWS](https://docs.databricks.com/applications/mlflow/tracking.html#notebook-experiments)|[Azure](https://docs.microsoft.com/azure/databricks/applications/mlflow/tracking#notebook-experiments)|[GCP](https://docs.gcp.databricks.com/applications/mlflow/tracking.html#notebook-experiments)). This page allows you to compare runs and view details for specific runs.\n\n<img width=\"800\" src=\"https://docs.databricks.com/_static/images/mlflow/quickstart/compare-runs.png\"/>"],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"70e02a64-6878-4b9b-9297-5390c9e19ddc"}}},{"cell_type":"markdown","source":["### Load models\nYou can also access the results for a specific run using the MLflow API. The code in the following cell illustrates how to load the model trained in a given MLflow run and use it to make predictions. You can also find code snippets for loading specific models on the MLflow run page ([AWS](https://docs.databricks.com/applications/mlflow/tracking.html#view-notebook-experiment)|[Azure](https://docs.microsoft.com/azure/databricks/applications/mlflow/tracking#view-notebook-experiment)|[GCP](https://docs.gcp.databricks.com/applications/mlflow/tracking.html#view-notebook-experiment))."],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"78c381a0-15ef-4b8c-92a3-73261bf7160f"}}},{"cell_type":"code","source":["# After a model has been logged, you can load it in different notebooks or jobs\n# mlflow.pyfunc.load_model makes model prediction available under a common API\nmodel_loaded = mlflow.pyfunc.load_model(\n  'runs:/{run_id}/model'.format(\n    run_id=run.info.run_id\n  )\n)\n\npredictions_loaded = model_loaded.predict(X_test)\npredictions_original = model_2.predict(X_test)\n\n# The loaded model should match the original\nassert(np.array_equal(predictions_loaded, predictions_original))"],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"2d85461a-9f6d-43e4-abb5-0d72e1fe48a7"}},"outputs":[{"output_type":"display_data","metadata":{"application/vnd.databricks.v1+output":{"datasetInfos":[],"data":"<div class=\"ansiout\">2022/03/19 19:55:50 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:51 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:51 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:51 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:51 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:51 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:51 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:51 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:51 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:51 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:51 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:51 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:51 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:51 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:51 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:51 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:51 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:51 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:51 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:52 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:52 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:52 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:52 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:52 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n</div>","removedWidgets":[],"addedWidgets":{},"metadata":{},"type":"html","arguments":{}}},"output_type":"display_data","data":{"text/html":["<style scoped>\n  .ansiout {\n    display: block;\n    unicode-bidi: embed;\n    white-space: pre-wrap;\n    word-wrap: break-word;\n    word-break: break-all;\n    font-family: \"Source Code Pro\", \"Menlo\", monospace;;\n    font-size: 13px;\n    color: #555;\n    margin-left: 4px;\n    line-height: 19px;\n  }\n</style>\n<div class=\"ansiout\">2022/03/19 19:55:50 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:51 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:51 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:51 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:51 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:51 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:51 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:51 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:51 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:51 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:51 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:51 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:51 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:51 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:51 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:51 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:51 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:51 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:51 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:52 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:52 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:52 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:52 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:55:52 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n</div>"]}}],"execution_count":0},{"cell_type":"markdown","source":["## Part 2. Hyperparameter Tuning\nAt this point, you have trained a simple model and used the MLflow tracking service to organize your work. This section covers how to perform more sophisticated tuning using Hyperopt."],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"6eaefdfe-f00e-4e3b-b647-4ed56cb89b15"}}},{"cell_type":"markdown","source":["### Parallel training with Hyperopt and SparkTrials\n[Hyperopt](http://hyperopt.github.io/hyperopt/) is a Python library for hyperparameter tuning. For more information about using Hyperopt in Databricks, see the documentation ([AWS](https://docs.databricks.com/applications/machine-learning/automl-hyperparam-tuning/index.html#hyperparameter-tuning-with-hyperopt)|[Azure](https://docs.microsoft.com/azure/databricks/applications/machine-learning/automl-hyperparam-tuning/index#hyperparameter-tuning-with-hyperopt)|[GCP](https://docs.gcp.databricks.com/applications/machine-learning/automl-hyperparam-tuning/index.html#hyperparameter-tuning-with-hyperopt)).\n\nYou can use Hyperopt with SparkTrials to run hyperparameter sweeps and train multiple models in parallel. This reduces the time required to optimize model performance. MLflow tracking is integrated with Hyperopt to automatically log models and parameters."],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"112f48ac-e1dd-40e5-b40b-56266306130c"}}},{"cell_type":"code","source":["# Define the search space to explore\nsearch_space = {\n  'n_estimators': scope.int(hp.quniform('n_estimators', 20, 1000, 1)),\n  'learning_rate': hp.loguniform('learning_rate', -3, 0),\n  'max_depth': scope.int(hp.quniform('max_depth', 2, 5, 1)),\n}\n\ndef train_model(params):\n  # Enable autologging on each worker\n  mlflow.autolog()\n  with mlflow.start_run(nested=True):\n    model_hp = sklearn.ensemble.GradientBoostingClassifier(\n      random_state=0,\n      **params\n    )\n    model_hp.fit(X_train, y_train)\n    predicted_probs = model_hp.predict_proba(X_test)\n    # Tune based on the test AUC\n    # In production settings, you could use a separate validation set instead\n    roc_auc = sklearn.metrics.roc_auc_score(y_test, predicted_probs[:,1])\n    mlflow.log_metric('test_auc', roc_auc)\n    \n    # Set the loss to -1*auc_score so fmin maximizes the auc_score\n    return {'status': STATUS_OK, 'loss': -1*roc_auc}\n\n# SparkTrials distributes the tuning using Spark workers\n# Greater parallelism speeds processing, but each hyperparameter trial has less information from other trials\n# On smaller clusters or Databricks Community Edition try setting parallelism=2\nspark_trials = SparkTrials(\n  parallelism=8\n)\n\nwith mlflow.start_run(run_name='gb_hyperopt') as run:\n  # Use hyperopt to find the parameters yielding the highest AUC\n  best_params = fmin(\n    fn=train_model, \n    space=search_space, \n    algo=tpe.suggest, \n    max_evals=32,\n    trials=spark_trials)"],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"6d3f22d5-8217-42ad-bd78-fbf30ef5538c"}},"outputs":[{"output_type":"display_data","metadata":{"application/vnd.databricks.v1+output":{"datasetInfos":[],"data":"<div class=\"ansiout\">2022/03/19 19:56:00 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:56:00 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:56:00 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:56:00 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:56:00 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:56:00 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n\r  0%|          | 0/32 [00:00&lt;?, ?trial/s, best loss=?]\r  6%|▋         | 2/32 [00:16&lt;04:01,  8.03s/trial, best loss: -0.8958464465552758]\r  9%|▉         | 3/32 [00:23&lt;03:40,  7.62s/trial, best loss: -0.8958464465552758]\r 12%|█▎        | 4/32 [00:30&lt;03:26,  7.39s/trial, best loss: -0.9055061226825362]\r 16%|█▌        | 5/32 [00:34&lt;02:47,  6.22s/trial, best loss: -0.9055061226825362]\r 19%|█▉        | 6/32 [00:35&lt;01:56,  4.49s/trial, best loss: -0.9055061226825362]\r 22%|██▏       | 7/32 [00:38&lt;01:40,  4.01s/trial, best loss: -0.9055061226825362]\r 25%|██▌       | 8/32 [00:49&lt;02:29,  6.22s/trial, best loss: -0.9055061226825362]\r 28%|██▊       | 9/32 [00:50&lt;01:45,  4.61s/trial, best loss: -0.9055061226825362]\r 31%|███▏      | 10/32 [00:53&lt;01:30,  4.12s/trial, best loss: -0.9076876859693294]\r 34%|███▍      | 11/32 [00:54&lt;01:06,  3.17s/trial, best loss: -0.9076876859693294]\r 38%|███▊      | 12/32 [01:06&lt;01:57,  5.85s/trial, best loss: -0.9076876859693294]\r 41%|████      | 13/32 [01:11&lt;01:46,  5.61s/trial, best loss: -0.9076876859693294]\r 44%|████▍     | 14/32 [01:12&lt;01:16,  4.24s/trial, best loss: -0.9076876859693294]\r 47%|████▋     | 15/32 [01:18&lt;01:21,  4.79s/trial, best loss: -0.9076876859693294]\r 50%|█████     | 16/32 [01:24&lt;01:22,  5.17s/trial, best loss: -0.9076876859693294]\r 56%|█████▋    | 18/32 [01:30&lt;00:58,  4.17s/trial, best loss: -0.9076876859693294]\r 59%|█████▉    | 19/32 [01:39&lt;01:10,  5.41s/trial, best loss: -0.9076876859693294]\r 62%|██████▎   | 20/32 [01:47&lt;01:13,  6.10s/trial, best loss: -0.9076876859693294]\r 66%|██████▌   | 21/32 [01:53&lt;01:06,  6.09s/trial, best loss: -0.9076876859693294]\r 72%|███████▏  | 23/32 [01:58&lt;00:40,  4.53s/trial, best loss: -0.9133204108491646]\r 75%|███████▌  | 24/32 [02:03&lt;00:37,  4.66s/trial, best loss: -0.9133204108491646]\r 78%|███████▊  | 25/32 [02:18&lt;00:51,  7.29s/trial, best loss: -0.9133204108491646]\r 81%|████████▏ | 26/32 [02:20&lt;00:35,  5.88s/trial, best loss: -0.9133239871824216]\r 84%|████████▍ | 27/32 [02:23&lt;00:25,  5.09s/trial, best loss: -0.9156342984664685]\r 88%|████████▊ | 28/32 [02:28&lt;00:20,  5.07s/trial, best loss: -0.9156342984664685]\r 91%|█████████ | 29/32 [02:43&lt;00:23,  7.93s/trial, best loss: -0.9156342984664685]\r 94%|█████████▍| 30/32 [02:47&lt;00:13,  6.79s/trial, best loss: -0.9156342984664685]\r 97%|█████████▋| 31/32 [02:49&lt;00:05,  5.38s/trial, best loss: -0.916074187457084] \r100%|██████████| 32/32 [02:55&lt;00:00,  5.57s/trial, best loss: -0.916074187457084]\r100%|██████████| 32/32 [02:55&lt;00:00,  5.50s/trial, best loss: -0.916074187457084]\nTotal Trials: 32: 32 succeeded, 0 failed, 0 cancelled.\n2022/03/19 19:58:57 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:58:57 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:58:57 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n</div>","removedWidgets":[],"addedWidgets":{},"metadata":{},"type":"html","arguments":{}}},"output_type":"display_data","data":{"text/html":["<style scoped>\n  .ansiout {\n    display: block;\n    unicode-bidi: embed;\n    white-space: pre-wrap;\n    word-wrap: break-word;\n    word-break: break-all;\n    font-family: \"Source Code Pro\", \"Menlo\", monospace;;\n    font-size: 13px;\n    color: #555;\n    margin-left: 4px;\n    line-height: 19px;\n  }\n</style>\n<div class=\"ansiout\">2022/03/19 19:56:00 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:56:00 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:56:00 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:56:00 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:56:00 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:56:00 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n\r  0%|          | 0/32 [00:00&lt;?, ?trial/s, best loss=?]\r  6%|▋         | 2/32 [00:16&lt;04:01,  8.03s/trial, best loss: -0.8958464465552758]\r  9%|▉         | 3/32 [00:23&lt;03:40,  7.62s/trial, best loss: -0.8958464465552758]\r 12%|█▎        | 4/32 [00:30&lt;03:26,  7.39s/trial, best loss: -0.9055061226825362]\r 16%|█▌        | 5/32 [00:34&lt;02:47,  6.22s/trial, best loss: -0.9055061226825362]\r 19%|█▉        | 6/32 [00:35&lt;01:56,  4.49s/trial, best loss: -0.9055061226825362]\r 22%|██▏       | 7/32 [00:38&lt;01:40,  4.01s/trial, best loss: -0.9055061226825362]\r 25%|██▌       | 8/32 [00:49&lt;02:29,  6.22s/trial, best loss: -0.9055061226825362]\r 28%|██▊       | 9/32 [00:50&lt;01:45,  4.61s/trial, best loss: -0.9055061226825362]\r 31%|███▏      | 10/32 [00:53&lt;01:30,  4.12s/trial, best loss: -0.9076876859693294]\r 34%|███▍      | 11/32 [00:54&lt;01:06,  3.17s/trial, best loss: -0.9076876859693294]\r 38%|███▊      | 12/32 [01:06&lt;01:57,  5.85s/trial, best loss: -0.9076876859693294]\r 41%|████      | 13/32 [01:11&lt;01:46,  5.61s/trial, best loss: -0.9076876859693294]\r 44%|████▍     | 14/32 [01:12&lt;01:16,  4.24s/trial, best loss: -0.9076876859693294]\r 47%|████▋     | 15/32 [01:18&lt;01:21,  4.79s/trial, best loss: -0.9076876859693294]\r 50%|█████     | 16/32 [01:24&lt;01:22,  5.17s/trial, best loss: -0.9076876859693294]\r 56%|█████▋    | 18/32 [01:30&lt;00:58,  4.17s/trial, best loss: -0.9076876859693294]\r 59%|█████▉    | 19/32 [01:39&lt;01:10,  5.41s/trial, best loss: -0.9076876859693294]\r 62%|██████▎   | 20/32 [01:47&lt;01:13,  6.10s/trial, best loss: -0.9076876859693294]\r 66%|██████▌   | 21/32 [01:53&lt;01:06,  6.09s/trial, best loss: -0.9076876859693294]\r 72%|███████▏  | 23/32 [01:58&lt;00:40,  4.53s/trial, best loss: -0.9133204108491646]\r 75%|███████▌  | 24/32 [02:03&lt;00:37,  4.66s/trial, best loss: -0.9133204108491646]\r 78%|███████▊  | 25/32 [02:18&lt;00:51,  7.29s/trial, best loss: -0.9133204108491646]\r 81%|████████▏ | 26/32 [02:20&lt;00:35,  5.88s/trial, best loss: -0.9133239871824216]\r 84%|████████▍ | 27/32 [02:23&lt;00:25,  5.09s/trial, best loss: -0.9156342984664685]\r 88%|████████▊ | 28/32 [02:28&lt;00:20,  5.07s/trial, best loss: -0.9156342984664685]\r 91%|█████████ | 29/32 [02:43&lt;00:23,  7.93s/trial, best loss: -0.9156342984664685]\r 94%|█████████▍| 30/32 [02:47&lt;00:13,  6.79s/trial, best loss: -0.9156342984664685]\r 97%|█████████▋| 31/32 [02:49&lt;00:05,  5.38s/trial, best loss: -0.916074187457084] \r100%|██████████| 32/32 [02:55&lt;00:00,  5.57s/trial, best loss: -0.916074187457084]\r100%|██████████| 32/32 [02:55&lt;00:00,  5.50s/trial, best loss: -0.916074187457084]\nTotal Trials: 32: 32 succeeded, 0 failed, 0 cancelled.\n2022/03/19 19:58:57 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:58:57 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:58:57 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n</div>"]}}],"execution_count":0},{"cell_type":"markdown","source":["### Search runs to retrieve the best model\nBecause all of the runs are tracked by MLflow, you can retrieve the metrics and parameters for the best run using the MLflow search runs API to find the tuning run with the highest test auc.\n\nThis tuned model should perform better than the simpler models trained in Part 1."],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"bae7ad39-0eea-4dcd-a58a-dcfc723ba91f"}}},{"cell_type":"code","source":["# Sort runs by their test auc; in case of ties, use the most recent run\nbest_run = mlflow.search_runs(\n  order_by=['metrics.test_auc DESC', 'start_time DESC'],\n  max_results=10,\n).iloc[0]\nprint('Best Run')\nprint('AUC: {}'.format(best_run[\"metrics.test_auc\"]))\nprint('Num Estimators: {}'.format(best_run[\"params.n_estimators\"]))\nprint('Max Depth: {}'.format(best_run[\"params.max_depth\"]))\nprint('Learning Rate: {}'.format(best_run[\"params.learning_rate\"]))\n\nbest_model_pyfunc = mlflow.pyfunc.load_model(\n  'runs:/{run_id}/model'.format(\n    run_id=best_run.run_id\n  )\n)\nbest_model_predictions = best_model_pyfunc.predict(X_test[:5])\nprint(\"Test Predictions: {}\".format(best_model_predictions))"],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"5ea75b75-0439-4fa2-9f8c-6bbd2b586719"}},"outputs":[{"output_type":"display_data","metadata":{"application/vnd.databricks.v1+output":{"datasetInfos":[],"data":"<div class=\"ansiout\">2022/03/19 19:59:37 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:37 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:37 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\nBest Run\nAUC: 0.9176370450904098\nNum Estimators: 895\nMax Depth: 5\nLearning Rate: 0.17522781807792243\n2022/03/19 19:59:37 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:37 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:37 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:38 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:38 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:38 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:38 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:38 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:38 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:38 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:38 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:38 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:38 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:38 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:38 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:38 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:38 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:38 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:38 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:38 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:38 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:38 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:38 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:38 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\nTest Predictions: [False False False  True  True]\n</div>","removedWidgets":[],"addedWidgets":{},"metadata":{},"type":"html","arguments":{}}},"output_type":"display_data","data":{"text/html":["<style scoped>\n  .ansiout {\n    display: block;\n    unicode-bidi: embed;\n    white-space: pre-wrap;\n    word-wrap: break-word;\n    word-break: break-all;\n    font-family: \"Source Code Pro\", \"Menlo\", monospace;;\n    font-size: 13px;\n    color: #555;\n    margin-left: 4px;\n    line-height: 19px;\n  }\n</style>\n<div class=\"ansiout\">2022/03/19 19:59:37 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:37 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:37 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\nBest Run\nAUC: 0.9176370450904098\nNum Estimators: 895\nMax Depth: 5\nLearning Rate: 0.17522781807792243\n2022/03/19 19:59:37 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:37 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:37 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:38 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:38 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:38 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:38 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:38 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:38 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:38 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:38 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:38 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:38 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:38 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:38 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:38 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:38 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:38 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:38 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:38 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:38 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:38 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:38 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\n2022/03/19 19:59:38 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:\n&#39;JavaPackage&#39; object is not callable\nTest Predictions: [False False False  True  True]\n</div>"]}}],"execution_count":0},{"cell_type":"markdown","source":["### Compare multiple runs in the UI\nAs in Part 1, you can view and compare the runs in the MLflow experiment details page, accessible via the external link icon at the top of the **Experiment** sidebar. \n\nOn the experiment details page, click the \"+\" icon to expand the parent run, then select all runs except the parent, and click **Compare**. You can visualize the different runs using a parallel coordinates plot, which shows the impact of different parameter values on a metric. \n\n<img width=\"800\" src=\"https://docs.databricks.com/_static/images/mlflow/quickstart/parallel-plot.png\"/>"],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"32be40f4-ba23-4512-817e-ab62e9a85825"}}}],"metadata":{"application/vnd.databricks.v1+notebook":{"notebookName":"Demo ML","dashboards":[],"notebookMetadata":{"pythonIndentUnit":2},"language":"python","widgets":{},"notebookOrigID":2445369866944265}},"nbformat":4,"nbformat_minor":0}
